### ISSUE TITLE
Price Sync

### ISSUE THREAD

**Issue by heshamMassoud** [commercetools/commercetools-sync-java#101]
Currently the sync always updates prices with `setPrices` update action regardless if needed or not. It should, however, calculate update actions, and only issue and update request if needed. 

### Price update actions
- [x] addPrice
- [x] setPrices: (should only be used in the case of no existing prices at all: https://github.com/sphereio/sphere-product-import/issues/117, `ChangePrice` should be used instead)
- [x] changePrice
- [x] removePrice
- [x] setProductPriceCustomType
- [ ] setProductPriceCustomField
- [ ] setDiscountedPrice

**Note:** Price order should not matter.

### Prices are uniquely identified by a combination of
1. `country`
2. `customerGroup`
3. `channel`
4. `validFrom`
5. `validUntil`

----------
1. The price matcher should first find the most precise match which has a match having the same exact 5 field values.
2. If not it, the next precise match would be one which has the same exact first 3 field values (`country`, `customerGroup` and `channel`).
3. If not, then there is no match and the prices should be created ( @butenkor right?)
------------ 
**Update**
Price matching would be based on above logic and not on key matching.

**Comment by butenkor** [comment]
Correct. Additionally there should be flag `allowPriceRemoval`, which by default is set to `true` and would remove all prices in existing variant which are not defined in a new variant draft.

**Comment by heshamMassoud** [comment]
> Additionally there should be flag `allowPriceRemoval`, which by default is set to true and would remove all prices in existing variant which are not defined in a new variant draft.

We have discussed earlier general options as boolean flags in the sync lib like: 
1. removeOtherLocales
2. removeOtherSetEntries
3. removeOtherCollectionEntries
4. removeOtherProperties

So prices would fall in the "removeOtherCollectionEntries" case. However, it would be better if we can specify exactly which collectionEntries to remove extra stuff from.  For example, only remove extra prices, but don't remove extra images. This I guess would mean something as described in this issue: https://github.com/commercetools/commercetools-sync-java/issues/51 . So changing all these boolean flags to blacklist of which resources to remove extra locales/set entries/collection entries/ properties. 

What do you think?

**Comment by heshamMassoud** [comment]
@butenkor wouldn't have a price key save us all the hassle of checking the preciseness of price matching described in the issue description?

**Comment by butenkor** [comment]
I also think that issue #51 is more suitable for blacklisting instead of separate boolean flags.
Keys for prices would be simpler indeed.

**Comment by heshamMassoud** [comment]
Seems that keys could be added to prices on CTP. Not sure, if it makes sense to start implementing this matching logic, which would be removed when keys are added.

**Comment by heshamMassoud** [comment]
released in 1.0.0-M13
