### ISSUE TITLE
Make setting IT projects credentials more convenient

### ISSUE THREAD

**Issue by heshamMassoud** [commercetools/commercetools-sync-java#105]
### Description
Make setting IT projects credentials more convenient by
1. Validate if env vars are set or not and accordingly print a descriptive error if they are not set.
2. Enable setting credentials through Java CLI options, then property file then fallback to environment variables. 

### Current Behaviour
Now credentials are only provided through environment variables.

**Comment by heshamMassoud** [comment]
@andrii-kovalenko-ct can you please note down here details of the change you implemented regarding setting up the CTP client for ITs?

**Comment by andrii-kovalenko-ct** [comment]
@heshamMassoud 
https://github.com/commercetools/commercetools-sync-java/commit/bd501ea1b38ae806efb20c943ef7d9e52d2e2f64

**Comment by heshamMassoud** [comment]
I reopened since it's still not on master.

**Comment by andrii-kovalenko-ct** [comment]
ah, i thought we close it when it is merged to target branch (MVP in our case)

**Comment by heshamMassoud** [comment]
bd501ea closes this issue
