### ISSUE TITLE
Improve product sync implementation

### ISSUE THREAD

**Issue by heshamMassoud** [commercetools/commercetools-sync-java#108]
Consider making for sync product util a builder that will create for each `syncProduct` call internal class variables:

  - [ ] productVariantAttributes: containing attribute information (`isRequired`, `sameForAll`)
  - [ ] alreadyDefinedSameForAllAttributeNames (so that we omit generation of too many unneeded sameForAll `setAttributeForAllVariants` update actions). Right now, we have to filter them out in the end of the sync from the update actions array.
  - [ ] `buildProductVariantAttributesUpdateActions()`: search attribute by name is a linear operation, which may grow qurdraticaly if number of attributes is large.

**Comment by ahmetoz** [comment]
The issue looks not up to date according to the code, and hard to know what is meant, so I am closing it.
