### ISSUE TITLE
I want to remove the products from Category

### ISSUE THREAD

**Issue by satyam21041997** [commercetools/commercetools-sync-java#1080]
Hi,
I have a list of product id/key for which I want to remove from the assigned category.
Can you help me out with how can I remove all the product's category in one go?

**Comment by salander85** [comment]
Hi @satyam21041997 ,

thanks for your request. The sync-java API helps to sync data from external into CTP project. Can you please describe your use case? What are you trying to achieve with sync-java?

Regards, Sarah
