### ISSUE TITLE
Migration from java sdk-v1 to sdk-v2 status?

### ISSUE THREAD

**Issue by th1nkgr33n** [commercetools/commercetools-sync-java#1085]
Hello together,

I'm currently in the process to migrate a kind of abandoned java project which uses this sync-sdk to update types and products in commercetools.

I haven't been in touch with the commercetools sdk ecosystem for a while and the last days raised some questions.
- Whats the status of this project in relation to "are there maintainer?" or "ist this project still maintained?"
- Whats the roadmap in this project to migrate completely to the sdk2? With all the things the migration guide from commercetools suggests?
- Or is it enough to add the compact layer? 
- How long will be the compact layer supported?
- Is there any kind of community to ask for help? Discord, Slack, etc?

Thanks for help, I'm at the start to get again more deeper to the ecosystem and a little bit of booster would be a great help.
Kind Regards

**Comment by jenschude** [comment]
Hi

> - Whats the status of this project in relation to "are there maintainer?" or "ist this project still maintained?"

Yes it's still maintained.

> - Whats the roadmap in this project to migrate completely to the sdk2? With all the things the migration guide from commercetools suggests?

Yes the project is being migrated. There is an active development branch for the v2 migration.

> - Or is it enough to add the compact layer?

The compat layer can be used in the meantime.

> - How long will be the compact layer supported?

There is no plan to sunset the Compat Layer as it's quite stable.

> - Is there any kind of community to ask for help? Discord, Slack, etc?

Atm there is no community channel. So either the GH issues or the support channel can be used.

**Comment by lojzatran** [comment]
Hi @th1nkgr33n,

The library is now migrated to java-sdk-v2. Hereby I'm closing this issue. Feel free to reopen it if you have further questions.
