### ISSUE TITLE
Query for used Custom Object keys can exceed API query string limit

### ISSUE THREAD

**Issue by Mercious** [commercetools/commercetools-sync-java#1109]
While using the sync library in version **10.0.0-beta.4** I encountered an issue with the ProductSync. It seems like if a batch of ProductDrafts that is trying to be synced uses a large amount of Custom Object references within the batch, the sync library produces a API Query Request that exceeds some query string limit (assumption). This results in the API responding with a 404 and the subsequent sync library code then throws a SyncException: Failed to build a cache of keys to ids.

While debugging this issue it seems like the possible culprit could be in **CustomObjectServiceImpl::fetchMatchingCustomObjects**. This method calls it's super-method **BaseService::fetchMatchingResources**, which does actually chunk the batch of objects to retrieve into chunks of size 250. However, it calls the super-method by passing a _keysQueryMapper_ that ignores the chunking that is done and instead builds a query with the full list of identifiers that were originally passed to the method. So it effectively builds query that are too long. This will also build multiple, identical queries, one for each chunk-size that the chunking logic of the BaseService does. 
The fix is likely just exchanging this one variable for the actual lambda parameter.

**Comment by lojzatran** [comment]
Hi @Mercious 

Thank you for reporting. We will look at this issue.
