### ISSUE TITLE
Products with product references are not synced

### ISSUE THREAD

**Issue by dfrommi** [commercetools/commercetools-sync-java#1127]
**Describe the bug**
Products referencing other products are not synced. They are skipped due to unknown references.

**To Reproduce**
1. Call `ProductSync.sync()` for a product that references other products
2. Changes are not synchronised

**Expected behavior**
References to other products should be resolved and the changes synchronised. A matching by product-key is expected.
(The bug is *not* about changes in referenced products. The input-product is not synchronised.)

**Additional context**
Analysis-result so far:
1. Product-references are collected in `ProductBatchValidator.getReferencedKeysWithReferenceTypeId()`. 
2. The `id` of the products are returned, instead of the `key`
3. `BaseService.cacheKeysToIdsUsingGraphQl()` filters for keys on the target-project, so it doesn't find the referenced products and thus they are not available in cache
4. This leads to `missingReferencedProductKeys` to be non-empty in `ProductSync.syncOrKeepTrack()` which prevents the sync

What in my opinion needs to be done:
- Product-keys have to be resolved from the *source-project* by ID (keys are not directly available in references)
- Product-IDs have to be resolved by the keys resolved in the first step on the *target project*
- Matching between old and new to find differences, then using the target-projects IDs

**Comment by salander85** [comment]
Hi @dfrommi ,
thank you for reporting this issue.
We will check it and let you know the results.

To help us reproducing your issue please let us know
- the version you are using
- the JSON of the product you are trying to sync
- the referenced products already existing in your target project when you try to sync?

Regards,
Sarah

**Comment by salander85** [comment]
Hi @dfrommi ,
thanks for your response. The posted information should be good enough.
Only one question i need to know is, are the referenced products already existing in your target project when you try to sync?
Regards.

**Comment by dfrommi** [comment]
Hello @salander85 
Yes they are and also published.

**Comment by dfrommi** [comment]
Thanks you so much for your quick help!
On a first quick test, it updates something. Have to look closer into it, but looks promising as of now.

And yes, the ProductTransformUtils-method did the trick. We were using `ProductReferenceResolutionUtils.mapToProductDrafts` from the SDK instead, which is not resolving keys.

**Comment by dfrommi** [comment]
I've done more tests and the problem is resolved. Thank you very much, @salander85 

To create the `ProductDraft`, use `com.commercetools.sync.products.utils.ProductTransformUtils#toProductDrafts`.

(*Don't use* ProductReferenceResolutionUtils.mapToProductDrafts from the CT SDK)
