### ISSUE TITLE
Product variant sync: implement moveImageToPosition 

### ISSUE THREAD

**Issue by andrii-kovalenko-ct** [commercetools/commercetools-sync-java#114]
Move image to position update action hasn't been implemented jet in  still not implemented in milestone [1.0.0-M2-beta](https://github.com/commercetools/commercetools-sync-java/milestone/6), see comments:
https://github.com/commercetools/commercetools-sync-java/issues/100#issuecomment-331830438

The solution https://github.com/commercetools/commercetools-sync-java/issues/100#issuecomment-332126107 :
> On second thoughts moveImageToPosition can still be implemented. Since the image position is the position/order of the image in the images array of the variant.

**Comment by heshamMassoud** [comment]
#123 closes this issue
