### ISSUE TITLE
Reference resolution fails

### ISSUE THREAD

**Issue by valtechtmn** [commercetools/commercetools-sync-java#1151]
Hi,

I'm attempting to sync 2 commercetools environment's data such as product, category, inventory... Everything else custom types, product types, tax category and such are 'synced' by continuous deployment via terraform.

I have category A present in both env and in the source env I add a custom type to this category. Said custom type is present in target env and both have the same key, I triple checked that. When I attempt a sync in those conditions, category A is not synced and the following error ensues :

```
2024-02-06 18:17:40  ERROR PhoenixCommercetoolsSync:144 - Failed to update Category with key: 'test-cat-sync'. Reason: com.commercetools.api.client.error.BadRequestException: detailMessage: Client error response [url] https://api.us-central1.gcp.commercetools.com/<project-key>/categories/6a07797d-071b-4476-ab26-f79f361c2f9e [status code] 400 [reason phrase] Bad Request
summary: POST https://api.us-central1.gcp.commercetools.com/<project-key>/categories/6a07797d-071b-4476-ab26-f79f361c2f9e failed  with response code 400 with X-Correlation-ID `{key=x-correlation-id, value=<project-key>/10c38aac-7c9a-4355-91c3-bb104d0a167f}` on 2024-02-06T18:17:37.852712386Z
http response formatted body: {
  "statusCode" : 400,
  "message" : "The type with the id '29e37399-8964-4444-8901-aa5346383991' was not found",
  "errors" : [ {
    "code" : "InvalidOperation",
    "message" : "The type with the id '29e37399-8964-4444-8901-aa5346383991' was not found",
    "action" : {
      "type" : {
        "id" : "29e37399-8964-4444-8901-aa5346383991",
        "typeId" : "type"
      },
      "fields" : {
        "isPrimaryCategory" : true
      },
      "action" : "setCustomType"
    },
    "actionIndex" : 1
  } ]
}

```

My understanding is that the commercetools-sync-java utility method `CategoryTransformUtils.toCategoryDrafts` would take care of fetching the key associated with the custom type ID and using that would be able to find the corresponding ID on the target env. Am I mistaken ? And if so what am I expected to do to make sure the custom type is properly mapped with the corresponding one in the target env.

Let me know if you need more detailed info about anything.
Thanks.

P.S: I thought for a moment that my API client didn't have enough right for the utility method to make the graphQL request necessary to get the key/id pair but I would assume if that was the case I would see some sort of error in my logs around that ?

**Comment by valtechtmn** [comment]
Hi @lojzatran,

Thanks for your reply, the test does seem to capture precisely what I'm trying to do. So obviously it's something that I'm doing wrong. I'll dig deeper tomorrow to find any more subtle differences and update or close this depending on my findings.

**Comment by valtechtmn** [comment]
Well, one of the only subtle thing that was different between your case and mine is the api client scopes and that proved to be the problem, view_types was necessary. Strangely enough no error was shown, I assume because of the way graphQL handle errors in generals retrieving zero result rather than throwing an error.

Apologies for the waste of time, hopefully it can serve someone else in the future.
Thanks again for all your hard work on this project.

**Comment by valtechtmn** [comment]
@lojzatran 

While I have your attention I wanted to ask a quick question without creating another thread :
I see there is support for sync of cart discounts but what about product discounts and discount codes. Are these not supported ? Are there plan to support them ?
Thanks again !

**Comment by lojzatran** [comment]
Hi @valtechtmn,
Currently we don't provide support for product discounts nor discount codes.
However, please feel free to create a support ticket for adding the support of product discounts and discount codes here, https://support.commercetools.com/
Thank you.
