### ISSUE TITLE
Is it possible partial update product without providing product-type?

### ISSUE THREAD

**Issue by gamjeon** [commercetools/commercetools-sync-java#1161]
**Description**
I want to partial update product, but if I don't fill in product-type or I fill a wrong product-type in productDraft, This sync will always throw an exception like ```Failed to resolve 'product-type' resource identifier on ProductDraft with key:'0222222'. Reason: Product type with key 'standard-products' doesn't exist.```

From [Http Api ducoment](https://docs.commercetools.com/api/projects/products#update-product-by-key) I think it might be possible to update product without product-type key. Just have no idea how could I do that with this sdk.

**Code snippet**
```
ProductVariantDraft productVariantDraft = ProductVariantDraftBuilder.of()
            .key(product.getErpMaterialId())
            .sku(product.getErpMaterialId())
            .attributes(Arrays.asList(infoAttr))
            .build();

        ProductDraft productDraft = ProductDraftBuilder.of()
            .productType(standardProductType) // How can I don't fill any field here but update product
            .key(product.getKey())
            .slug(LocalizedString.ofEnglish("slug"))
            .name(LocalizedString.ofEnglish("name")))
            .masterVariant(productVariantDraft)
            .build();

        new ProductSync(productSyncOptions).sync(productDrafts).toCompletableFuture().join();
```

**Comment by lojzatran** [comment]
Hi @gamjeon 

Thank you for the request.

Unfortunately this tool does not allow what you are requesting.

Reason: The main goal of this tool is to have resources synchronized = the source and the target resources have to be the same. To achieve this in a product we need a product type, for example to know which attributes are same for all as they have different update actions. Therefore you must fill in the correct product type.

**Comment by lojzatran** [comment]
Hi @gamjeon 

I‘m closing this issue now. If you have further questions, feel free to reply here.
