### ISSUE TITLE
Consider code generation

### ISSUE THREAD

**Issue by hajoeichler** [commercetools/commercetools-sync-java#12]
We have a RAML definition of our API + some annotated Java Interfaces we already use to generate Java and PHP code from. Please have a look at it.

//cc @katmatt and @jayS-de

**Comment by heshamMassoud** [comment]
Hi @hajoeichler,

I am not sure how these generated classes from the API would be of use to this library. Could you please elaborate what you mean?

FYI, this is what the library of this repo does:

This library is intended to be used to sync data from a **source** (which could either be another CT project or a data feed that has already been mapped to JVM-SDK objects) to a **target** CT project.

For example, to sync **categories**
1. **From a data feed (CSV, XML, etc..)**
The user of the library would first map the data into JVM-SDK draft objects and then use this library (commercetools-sync-java), by passing to it a list of `CategoryDraft` objects. The library would, in turn, calculate update actions for the Categories on the target CT project and do the updates.

2. **From another CT project**
The user of the library would pass a list of `Category` objects. The library would, in turn, calculate update actions for the Categories on the target CT project and do the updates.

It is intended as one place for all sync modules of CTP resources e.g. products, stocks, etc..
Like what these modules do NodeJS application: https://github.com/sphereio/sphere-category-sync and https://github.com/sphereio/sphere-product-import

The library would also provide utilities to convert resources to the resource drafts (for example, Category to CategoryDraft) to be able to customise any fields in the drafts syncing to the target project.

**Comment by katmatt** [comment]
Hi @heshamMassoud,

I think that we at least could make your job a little bit easier by implementing [Copy factory method from resource to draft](https://github.com/commercetools/commercetools-jvm-sdk/issues/1364).

What do you think?

**Comment by heshamMassoud** [comment]
Hi @katmatt, we exactly wanted to have this functionality and we were going to implement it as an additional utils for this lib. But if it would be built-in the JVM SDK, then it would be more convenient and of great help to us! :)

**Comment by katmatt** [comment]
Hi @heshamMassoud,

Great and nice to hear that it's useful to you. I've pushed a working version for `CategoryDraftBuilder` to https://github.com/commercetools/commercetools-jvm-sdk/tree/copy-factory-methods. It's an extension to our code generator and just requires a little additional effort if we want to extend it to more types. 

So let me know if you like it, then we can discuss for which types you require this functionality and then we can decide how to proceed.

And let's see which patterns you discover when you implement the update action calculator, I really like the idea. And we are still open to discuss options to generate more code ;-)

**Comment by butenkor** [comment]
@katmatt Thanks. We need copy functionality for product type, product, inventories and categories for now. When are you going to release you PR?

**Comment by katmatt** [comment]
@butenkor I checked the additional types you requested and product type, inventory entry and categories already work with the code generator on our branch. But product requires some additional effort (attributes are generic). I have to think about it, but hope to have support for product at the end of this week.

**Comment by heshamMassoud** [comment]
Hi @katmatt, do you know by when will the SDK support copying for products as well?

**Comment by katmatt** [comment]
@heshamMassoud I wasn't aware that you still need it. And we're very busy at the moment and can't support you. And our code generator is too limited to support the complex structure of a product. That means that the code has to be code manually. And we always welcome PRs and let us know if we can assist you in adding the copy product feature to our SDK.

**Comment by ahmetoz** [comment]
I'm closing this issue because the content here is outdated.
