### ISSUE TITLE
Allow blacklisting and whitelisting of particular product update actions

### ISSUE THREAD

**Issue by butenkor** [commercetools/commercetools-sync-java#122]
For example if following option is set: `blacklist: ["prices"]` java sync would not update, create, delete any prices. Whole price comparison may be skipped here.  I option `whitelist: ["prices"]` is set than only price update actions should be calculated and nothing else.

**Comment by heshamMassoud** [comment]
@butenkor shall we give the whitelist precedence over the blacklist? For example, if the options has supplied both `whitelist["images", "attributes"]` and `blacklist["prices"]`. Does it mean in that case that the sync will only calculate update actions for images and attributes and ignore the blacklist completely?

**Comment by butenkor** [comment]
I think it does not make sense to set both white- and blacklist. We could add special builder, which allows to set only one of options but not both.

**Comment by heshamMassoud** [comment]
#124 closes this issue
