### ISSUE TITLE
Update actions order to CTP is significant.

### ISSUE THREAD

**Issue by heshamMassoud** [commercetools/commercetools-sync-java#13]
Update actions on a resource should always be ordered as follows:-

1. Remove
2. Change/set
3. Add new
4. (in case of assets): Change Order.

**Comment by butenkor** [comment]
@heshamMassoud Would be good if in the future you could also provide why. Related: https://github.com/sphereio/sphere-node-sdk/issues/130

**Comment by heshamMassoud** [comment]
See also: SUPPORT-4128

**Comment by butenkor** [comment]
Fix with: https://github.com/commercetools/commercetools-sync-java/pull/508
