### ISSUE TITLE
Re-factor all collect(toList()) to avoid immutability issues

### ISSUE THREAD

**Issue by andrii-kovalenko-ct** [commercetools/commercetools-sync-java#135]
JDK method [`Collectors#toList`](https://docs.oracle.com/javase/8/docs/api/java/util/stream/Collectors.html#toList--) doesn't guarantee any type mutability, thread-safety or other values of the List returned.

Hence we should use the returned lists **only** as read only values.

Such kind of sources:
https://github.com/commercetools/commercetools-sync-java/blob/7bc08ee9bf29bf3193dd57d31cf6bb754b4e2d63/src/main/java/com/commercetools/sync/products/utils/ProductSyncUtils.java#L89-L101

should be completely avoided to `copyAll()` solutions

**Comment by ahmetoz** [comment]
I think for the SyncUtils it's ok to update the returned list, those kinds of issues are hard to resolve, we could refactor the sync utils only but it would not cover the issue. 
Maybe we need to take care of those concerns in PRs, not as a separate issue (boy-scout rule). Hereby I am closing the issue.
