### ISSUE TITLE
Support reference resolution in the key field not only id in ResourceIdentifiers

### ISSUE THREAD

**Issue by heshamMassoud** [commercetools/commercetools-sync-java#138]
**Edit: The task is resolved, so only parts are related to the API, not SDK anymore, when API adds support of ResourceIdentifier for PriceDraft#customerGroup we could close the issue. (Currently it's not clear when API will support this.)**

**Remaining work:**

Support requests (SUPPORT-9797, SUPPORT-9798) are opened for the problematic types/fields both API and SDK. Additionally, a GitHub issue is opened for jvm-sdk types: commercetools/commercetools-jvm-sdk#2052 (**Edit: The task is resolved, so only parts are related to the API, not SDK anymore.)**

----
### Description
Right now there are references which are of type `Reference` and other references which are of type `ResourceIdentifier`
1. `Reference` only supports `id` as a field.
2. `ResourceIdentifier`  supports `id` or `key` as a field.

On CTP in the future, all references should be changed to `ResourceIdentifier`.

It's quite confusing for the user of the sync library to put the key in the id field for reference resolution.

### Current Behaviour
Whether it's a resourceIdentifier or reference reference resolution is always done on the id field.

### Expected Behaviour
1. When the reference is of type `ResourceIdentifier`:
     - If the key field is set, sync lib should check if resource exists or not, and keep track of missing references (as done in cat sync) as it might be resolved in later batches.
     - If the id field is set, then it is an evidence of resource existence on CTP, so we can issue an update/create API request right away.
2. When the reference is of type `Reference`:
     - Do reference resolution as it currently is (key -> id mapping).

Related: #231

**Comment by butenkor** [comment]
As defined by @ahmetoz 

# References on commercetools-sync-java 

## [ProductDraft](https://docs.commercetools.com/http-api-projects-products.html#productdraft)
| field | commercetools type | required/optional | JVM SDK draft type | status | 
| --- | --- | --- | -- | -- | 
| productType  | ResourceIdentifier to a ProductType | Required   | `ResourceIdentifier<ProductType>`  | :heavy_check_mark: |
| categories  | Array of ResourceIdentifier for a Category  | Optional  | `Set<ResourceIdentifier<Category>>` | :heavy_check_mark: |
| taxCategory | ResourceIdentifier to a TaxCategory   | Optional |` ResourceIdentifier<TaxCategory>` | :heavy_check_mark: |
| state  | ResourceIdentifier to a State | Optional | ` Reference<State>` | :warning:  |

## [PriceDraft](https://docs.commercetools.com/http-api-projects-products.html#pricedraft)
| field | commercetools type | required/optional | JVM SDK draft type | status | 
| --- | --- | --- | -- | -- | 
| customerGroup  | **Reference** to a CustomerGroup  | Optional  | `Reference<CustomerGroup>`  | :warning:  |
| channel | ResourceIdentifier to a Channel | Optional  | `ResourceIdentifier<Channel>`  | :heavy_check_mark:  |

## [CustomFieldDraft](https://docs.commercetools.com/http-api-projects-custom-fields.html#customfieldsdraft)
| field | commercetools type | required/optional | JVM SDK draft type | status | 
| --- | --- | --- | -- | -- | 
| type  | ResourceIdentifier to a Type   | Required  | `ResourceIdentifier<Type>`  | :heavy_check_mark:  |

## [CategoryDraft](https://docs.commercetools.com/http-api-projects-categories.html#categorydraft)
| field | commercetools type | required/optional | JVM SDK draft type | status | 
| --- | --- | --- | -- | -- | 
| parent  | ResourceIdentifier to a Category  | Optional  | `ResourceIdentifier<Category>`  | :heavy_check_mark:  |

## [InventoryEntryDraft](https://docs.commercetools.com/http-api-projects-inventory.html#inventoryentrydraft)
| field | commercetools type | required/optional | JVM SDK draft type | status | 
| --- | --- | --- | -- | -- | 
| supplyChannel | ResourceIdentifier to a Channel  | Optional  | `ResourceIdentifier<Channel>`  | :heavy_check_mark:  |

## [CartDiscountDraft](https://docs.commercetools.com/http-api-projects-cartDiscounts#cartdiscountdraft)
| field | commercetools type | required/optional | JVM SDK draft type | status | 
| --- | --- | --- | -- | -- | 
| supplyChannel | ResourceIdentifier to a Channel  | Optional  | `ResourceIdentifier<Channel>`  | :heavy_check_mark:  |

# Not implemented yet

## [CustomerDraft](https://docs.commercetools.com/http-api-projects-customers#customerdraft) 
| field | commercetools type | required/optional | JVM SDK draft type | status | 
| --- | --- | --- | -- | -- | 
| stores | Array of ResourceIdentifier to a Store  | Optional  | `List<ResourceIdentifier<Store>>`  | :heavy_check_mark: |
| customerGroup |  ResourceIdentifier to a CustomerGroup | Optional | `ResourceIdentifier<CustomerGroup>` | :heavy_check_mark: |


## [ShoppingListDraft](https://docs.commercetools.com/http-api-projects-shoppingLists#shoppinglistdraft) 
| field | commercetools type | required/optional | JVM SDK draft type | status | 
| --- | --- | --- | -- | -- | 
| customer | ResourceIdentifier to a Customer | Optional | `Reference<Customer>`  | :warning: |

**Comment by butenkor** [comment]
As defined by @ahmetoz:

Support requests (SUPPORT-9797, SUPPORT-9798) are opened for the problematic types/fields both API and SDK and links are shared with @butenkor . Additionally, a GitHub issue is opened for jvm-sdk types: commercetools/commercetools-jvm-sdk#2052

**Comment by ahmetoz** [comment]
Released with: https://github.com/commercetools/commercetools-sync-java/blob/master/docs/RELEASE_NOTES.md#200---sept-14-2020

**Comment by ahmetoz** [comment]
The task is resolved, so only parts are related to the API, not SDK anymore, when API adds support of ResourceIdentifier for PriceDraft#customerGroup we could close the issue. (Currently, it's not clear when API will support this.)
