### ISSUE TITLE
Refactor createProductDraft and createProductDraftBuilder in ProductSyncMockUtils

### ISSUE THREAD

**Issue by heshamMassoud** [commercetools/commercetools-sync-java#152]
Unify the process of product draft creation for test utils by refactor `createProductDraft` and `createProductDraftBuilder` in `ProductSyncMockUtils`

**Comment by ahmetoz** [comment]
createProductDraft is using the createProductDraftBuilder inside and getting other references as params, for me it looks ok-ish, we might consider refactoring to make it better and less duplicate usage but does not look like sth important. 
I am closing the issue for now.
