### ISSUE TITLE
Gradle Task Execution Order

### ISSUE THREAD

**Issue by heshamMassoud** [commercetools/commercetools-sync-java#161]
### Description
- Organise and unify the location of specification of orders of gradle tasks should be in one place to facilitate reaching it later when needed in the future.
- PMD should run after CheckStyle before running the unit tests and integration tests. Currently PMD is run after the integration tests, which is not very good. Since the integration tests takes time. 

### Expected Behaviour
- The specification of tasks' order of execution should be specified concretley and in one location.
- PMD should run after CheckStyle before running the unit tests and integration tests.

### Current Behaviour
- Currently the order of execution is not concretely defined in one place. It is scattered around the gradle scripts and hard to find. 
- Currently PMD is run after the integration tests, which is not very good. Since the integration tests takes time. 

### Context
- It is hard to locate where the order of execution is currently specified, if any.
- It doesn't make sense to wait for +5mins for all tasks (CheckStyle, FindBugs, unit tests and integration tests) to run and then find there is a trivial bug discovered by PMD. It makes more sense to have all the static code analysers (CheckStyle, FindBugs and PMD) before the unit tests and integration tests.

**Comment by suryaprakashraja** [comment]
Hi @heshamMassoud, I can work this issue around.

**Comment by heshamMassoud** [comment]
sure! @suryaprakashraja please do :) Would appreciate it.
