### ISSUE TITLE
Make util out of CompletableFuture.completedFuture(Optional.empty()) 

### ISSUE THREAD

**Issue by heshamMassoud** [commercetools/commercetools-sync-java#164]
### Description
`CompletableFuture.completedFuture(Optional.empty())`
we have 5 usage in the main sources + 11 usages in the tests.

Maybe it is time to make a static util method for this
Could it be a constant? (e.g. could you reused already completed/joined future multiple times? guess yes, but not sure though)

Same for `completedFuture(null)`

  - [ ] add completed `Optional` future
  - [ ] add completed `null` future

### Related
https://github.com/commercetools/commercetools-sync-java/pull/154#discussion_r146798295

**Comment by andrii-kovalenko-ct** [comment]
```java
private static final CompletableFuture<Optional<?>> EMPTY = CompletableFuture.completedFuture(Optional.empty());

@Nonnull
@SuppressWarnings("unchecked")
public static <T> CompletableFuture<T> emptyOptionalCompletedFuture() {
    return (CompletableFuture<T>)EMPTY;
}
````

**Comment by whitemalt** [comment]
Hi let review on #328  

integration test appear fail since before commit I did

**Comment by heshamMassoud** [comment]
I reoppened it again because I have failed to notice this line: https://github.com/commercetools/commercetools-sync-java/pull/328/files#diff-a68bd83c3bb37d250217445d5d0117edR162

**Comment by ahmetoz** [comment]
It looks like it resolved in a PR but we have not considered closing this issue, I wonder who will close and when 🤔 
I also think using util for this is not necessary for now, it's already util getting rid of Optional.empty does not have much value.
