### ISSUE TITLE
Reference Resolution Improvement

### ISSUE THREAD

**Issue by heshamMassoud** [commercetools/commercetools-sync-java#166]
Some decisions need to be considered to improve reference resolution:
1. What happens if no id was found for the key required to be resolve. (Reference resolution exception? or no resolution should be done?) -- Currently, the draft is left without resolution.
2. What happens if id field was empty?. (Reference resolution exception? or no resolution should be done?) -- Currently, reference resolution exception is thrown.
3. Need to decide whether the sync resolvers should attempt to get the keys from the id fields or also the expanded references in the drafts?! -- Currently, it attempts on both for all references except for reference type attributes.
4. Also consider the UUID validation for keys that should be on id fields -- Currently, it validates UUID on key fields for all references except for reference type attributes.
5. [Refactor reference resolution of product references to fetch from cache right away (since the keys are now already cached by the BatchProcessor)](https://github.com/commercetools/commercetools-sync-java/pull/200)

**Comment by heshamMassoud** [comment]
1. #219 
2. Throw reference resolution exception - wrong data.
3. Only from the id field, remove code to fetch key from expansion.
4. Remove the uuid validation with the flag .allowUUIDs() (BREAKING CHANGE!)
5. Done

**Comment by ahmetoz** [comment]
This issue could be closed, we will handle #219 separately.
