### ISSUE TITLE
Use consistent naming in Tests and ITs setup and tearing down.

### ISSUE THREAD

**Issue by heshamMassoud** [commercetools/commercetools-sync-java#171]
Use consistent naming in Tests and ITs setup and tearing down: 

@Before usually is called setup()/setUp()
@After - teadDown()
@BeforeClass - setupClass()/beforeClass()
@AfterClass - tearDownClass()/afterClass()

**Comment by heshamMassoud** [comment]
I moved it to M15 since you started working on it.

**Comment by ahmetoz** [comment]
That issue is not looking important to me, imo it's ok-ish to have different names, it is enough that test hook names are easy to understand. We don't need a standard here.
