### ISSUE TITLE
Consider providing unit tests as examples for callback functions in dedicated files for better linking in docs. 

### ISSUE THREAD

**Issue by heshamMassoud** [commercetools/commercetools-sync-java#177]
Consider providing unit tests as examples for callback functions in dedicated files for better linking in docs. 

https://github.com/commercetools/commercetools-sync-java/pull/175#discussion_r148750393

Related: #189 #194

**Comment by ahmetoz** [comment]
Now, we are documenting the examples in the documentation in the markdown for each file.
