### ISSUE TITLE
Add optional callback "beforeCreateCallback"

### ISSUE THREAD

**Issue by butenkor** [commercetools/commercetools-sync-java#183]
### Description
As a sync user i would like to be able to change/extend POST payload to CTP API. Currently it is possible to provide custom update actions thorough `updateActionsCallback` which is called before product update but it is not possible to change/extend product payload/draft on product create request. 

### Current Behaviour
Product assets are not supported and there is no way to intercept sync process in order to add assets/modify payload for product create requests.

### Expected Behaviour
It should provide optional `beforeCreateCallback` which is called just before sync sends create product request to CTP API.

### Possible Solution
The logic for calculation of assets updates can be supplied thorough `updateActionsCallback` and for create it might be achieved thorough `beforeCreateCallback`. It might be reasonable to rename `updateActionsCallback` to `beforeUpdateCallback`.

**Comment by butenkor** [comment]
Parameters for callbacks:
`public List<UpdateActions<Product>> beforeUpdateCallback(List updateActions, newProductDraft, oldProduct)`

`public ProductDraft beforeCreateCallback(newProductDraft)`

**Comment by heshamMassoud** [comment]
- [ ] Template packaging structure should look as follows: 
    - `templates/callbacks/beforeupdatecallback`
    - `templates/callbacks/beforecreatecallback`
- [ ] Templates should have helper methods with flexible parameters (e.g. productType) and not exactly similar to the parameters of the callbacks (e.g. the TriFunction params)..
