### ISSUE TITLE
Complete full template example of SyncSingleLocale

### ISSUE THREAD

**Issue by heshamMassoud** [commercetools/commercetools-sync-java#189]
- [ ]  Make example full with localized attribute syncing.
- [ ]  Provide unit tests

Related #194

**Comment by heshamMassoud** [comment]
- [ ] Template packaging structure should look as follows: 
    - `templates/callbacks/beforeupdatecallback`
    - `templates/callbacks/beforecreatecallback`
- [ ] Templates should have helper methods with flexible parameters (e.g. `productType`) and not exactly similar to the parameters of the callbacks (e.g. the `TriFunction` params of the `beforeUpdateCallback`)..

**Comment by heshamMassoud** [comment]
waiting for this issue on the JVM SDK: 
bf339f7

**Comment by ahmetoz** [comment]
We have documentation for every callback on usage docs. I'm closing this out of date issue.
