### ISSUE TITLE
Change ctp client configuration

### ISSUE THREAD

**Issue by heshamMassoud** [commercetools/commercetools-sync-java#208]
These configuration on the ctp client should:
- [ ] timeout 30s -> 3 minutes
-> It's important to know, that the timeout value passed to the `SphereBlockingClient` here is only used when the method `executeBlocking()` is called. Therefore, its not actually used from within the sync. : 
https://github.com/commercetools/commercetools-sync-java/blob/482356facd204b6261120b5d022ee6ef4a8a5402/src/main/java/com/commercetools/sync/commons/utils/ClientConfigurationUtils.java#L45-L57

Therefore, to change the timeout value, this has to be changed on the default values of the underlying HTTP client here:
https://github.com/commercetools/commercetools-sync-java/blob/482356facd204b6261120b5d022ee6ef4a8a5402/src/main/java/com/commercetools/sync/commons/utils/ClientConfigurationUtils.java#L76-L86
using the following setters:
````java
                        .setRequestTimeout(30000)
                        .setConnectTimeout(1000)
                        .setReadTimeout(100)
````
The meaning and significance of each, need to be researched though.

- [ ] retryInterval start value 30s -> 200ms
- [ ] max retry count 50 -> 100
- [ ] The retry should also retry on all 5xx errors (including 500): 

https://github.com/commercetools/commercetools-sync-java/blob/b61de4b097fa87cf487f17cecf4260f8045fcc81/src/main/java/com/commercetools/sync/commons/utils/ClientConfigurationUtils.java#L92-L93

#### Update (14/02/2018) [Breaking change]
- Consider enforcing client creation in the sync library, rather than providing the option to inject the client to the library. 
##### Advantages
 1. This is to set the most optimal timeout defaults, max parallel requests, correct client decoration order
2. Encapsulate the complexity of the client configuration away from the user.
3. Configurable client configuration can then be exposed upon requests.
##### Disadvantages
1. If the client is used in another context other than the sync library, then it wouldn't be possible with the same client instance. Another client would have to be created.

**Comment by heshamMassoud** [comment]
More context:

https://github.com/sphereio/sphere-node-sdk/blob/master/src/coffee/repeater-task-queue.coffee
https://github.com/commercetools/zeg-cli/blob/master/lib/utils/common.js#L72

**Comment by ahmetoz** [comment]
We have updated our client configuration in the previous release v3.0.0, all notes in this issue are handled. I am closing this out of date issue for now.
