### ISSUE TITLE
Re-factor cache instantiation to avoid concurrent queries execution

### ISSUE THREAD

**Issue by andrii-kovalenko-ct** [commercetools/commercetools-sync-java#209]
Current Products/Categories/whatever caching is not efficient:

1) https://github.com/commercetools/commercetools-sync-java/blob/master/src/main/java/com/commercetools/sync/services/impl/ProductServiceImpl.java#L81
mutating inside lambdas - not a bug, but bad practice! This point navigated me to the next issue 

2) https://github.com/commercetools/commercetools-sync-java/blob/master/src/main/java/com/commercetools/sync/services/impl/ProductServiceImpl.java#L64-L83

as i understand, the whole method is intended to work in concurrent environment, thus might be called multiple times, but if two different threads call this method concurrently while `isCached == false` => `CtpQueryUtils.queryAll` will be called twice with the same arguments => absolutely inefficient considering that `queryAll` is quite a long lasting and resources consuming method + this will concurrently override the cache map!
We should either:
  - make locking/blocking for concurrent calls
  - return the same CompletionStage, if it has been created already. This solution will also  address the firs issue with `isCached` mutating inside lambdas.

The solution should be replicated for all other caching/blocking workflows in the project (Products/Categories/Inventories/whatever caching)

**Comment by heshamMassoud** [comment]
@andrii-kovalenko-ct 
> as i understand, the whole method is intended to work in concurrent environment

No, this method is not intended to be called concurrently as it's supposed to be called once per batch and we will state explicitly in the documentation that parallel batch calls are not supported as we scale by different approach. For more details, please see here: https://github.com/commercetools/commercetools-sync-java/issues/225#issuecomment-364398805

**Comment by ahmetoz** [comment]
In previous releases, v3.0.0 to v3.0.2 we introduce many changes for the performance of the caching also introduced an eviction strategy based on LRU, and cache size can be configurable with a sync option. So this issue is a bit outdated, I am closing it.
