### ISSUE TITLE
Reference Resolution: Handling of non-existent references

### ISSUE THREAD

**Issue by heshamMassoud** [commercetools/commercetools-sync-java#219]
Currently on reference resolution if the resource doesn't exist, reference resolution doesn't fail right away, but creates the draft with the reference not replaced and waits for the request to CTP to fail because of the wrong reference.

It should be more efficient and fail fast as soon as the resource is not found, before attempting to create/update the resource with the unresolved reference.

We should fail fast only on references which are not of the same type, the current sync is running. For example, product sync will fail fast for missing category, types, customer group references but **not** for product references (as it might be later resolved).

This doesn't apply in the product sync for product references and category sync for category references. In such cases, the sync process should keep track of unresolved references since they might come in later batches. This is already implemented in the category sync algorithm. But **not** in the product sync.

**Comment by ahmetoz** [comment]
Released with: https://github.com/commercetools/commercetools-sync-java/blob/master/docs/RELEASE_NOTES.md#200---sept-14-2020
