### ISSUE TITLE
Implement a ReferenceReplacementUtils base class where all the typed ones can extend.

### ISSUE THREAD

**Issue by heshamMassoud** [commercetools/commercetools-sync-java#222]
Implement a ReferenceReplacementUtils base class where all the typed ones can extend instead of having  totally independent static utils.

Benefits:
1. Reuse shared code.
2. Generic implementation will be easier (refer to https://github.com/commercetools/project-coeur-sync/pull/13/files#diff-6631965bc5aa9c32eb01531d6a952ec2R42)

**Comment by ahmetoz** [comment]
ReferenceResolutionUtils are not duplicating the code, the common things are shared already. I don't know the status in 2017, the issue looks a bit outdated to me.
