### ISSUE TITLE
Change `./travis-publish.sh` to a gradle script. 

### ISSUE THREAD

**Issue by heshamMassoud** [commercetools/commercetools-sync-java#229]
### Description

Change `./travis-publish.sh` to a gradle script. 

Advantages of having it as gradle (Thanks to @andrii-kovalenko-ct):-

1. having it is in gradle makes it platform independent, when bash scripts are platform dependent
bash language is less readable than groovy
2. less code because standard plugins incapsulate some logic
3. common plugins are pretty known by other developers, when custom script require time to investigate/understand how they work (that was the first thing i noticed: i need to read bash script, instead of some standard configuration, like in ant replace plugin)
3. common plugins are used/tested by hundreds of other users - bugs/vulnerabilities are discovered better/faster
4. we could try to create our own travis publish gradle plugin.

**Comment by heshamMassoud** [comment]
Eventually, also don't rely on CI tool's native callbacks (specifically: `on_success`), but rather rely fully on gradle.

**Comment by ahmetoz** [comment]
We migrated the script to the github actions: https://github.com/commercetools/commercetools-sync-java/commit/94666347bbd919c5469be3f53502dd2d2688ba50
