### ISSUE TITLE
New CTP Feature: parent of CategoryDraft is now a ResourceIdentifier instead of a Reference

### ISSUE THREAD

**Issue by heshamMassoud** [commercetools/commercetools-sync-java#231]
### Description
https://dev.commercetools.com/release-notes.html#release-notes---commercetools-platform---version-release-15-january-2018

### Consequences

- Reference of category parents of keys -> ids should not be needed anymore.
- Consistent logic to category type reference resolution.
- possible increase in efficiency reference resolution, since there is no need to fetch ids.

### Related
#166

**Comment by butenkor** [comment]
> possible increase in efficiency reference resolution, since there is no need to fetch ids

Not sure about that as you still need to fetch in order to know that desired key reference exists.

**Comment by ahmetoz** [comment]
Released with: https://github.com/commercetools/commercetools-sync-java/blob/master/docs/RELEASE_NOTES.md#200---sept-14-2020
