### ISSUE TITLE
Test latest compatibility with JVM SDK

### ISSUE THREAD

**Issue by heshamMassoud** [commercetools/commercetools-sync-java#236]
### Description

Setup a dedicated build for testing the library against the latest (~10) JVM SDK versions.
Automatically document the compatibility of the sync library with the latest JVM SDK version.

**Comment by ahmetoz** [comment]
We are keeping the SDK version up-to-date by using depandabot, imo we don't need to check the compatibility with the latest 10 version, not sure why it's opened as an issue. I'm closing the issue.
