### ISSUE TITLE
Update/Create products in parallel

### ISSUE THREAD

**Issue by lojzatran** [commercetools/commercetools-sync-java#238]
### Description
Create and update of product is now done sequentially. Maybe it's possible to do it in parallel.

### Current Behaviour
```java
@Nonnull
    private CompletionStage<Void> createOrUpdateProducts() {
        return productService.createProducts(draftsToCreate)
                             .thenAccept(createdProducts ->
                                 processCreatedProducts(createdProducts, draftsToCreate.size()))
                             .thenCompose(result -> syncProducts(productsToSync));
    }
```

### Expected Behaviour
`productService.createProducts(draftsToCreate)` and `syncProducts(productsToSync)` can be done with `CompletableFuture.allOf()`

**Comment by heshamMassoud** [comment]
released in v1.0.0-M14
