### ISSUE TITLE
Use google cloud KMS for encrypting travis secret env vars

### ISSUE THREAD

**Issue by heshamMassoud** [commercetools/commercetools-sync-java#247]
Use google cloud KMS for encrypting travis secret env vars instead of depending on travis' secret env vars:-
1. Makes the values recoverable in case sth happens to travis.
2. Devs with access to key chain would be able to see the actual encrypted values.

Related: https://github.com/commercetools/commercetools-sync-java/pull/240#pullrequestreview-95667512

**Comment by ahmetoz** [comment]
Does not look like a benefit to me, I am not concerned much for the security of Travis's secret env variables, soon we are planning to migrate to the GitHub actions, so this issue looks a bit over-engineering to me. I'm closing the issue.
