### ISSUE TITLE
create a dedicated util mapValuesToFutureOfListCompletedValues of of mapValuesToFutureOfCompletedValues

### ISSUE THREAD

**Issue by heshamMassoud** [commercetools/commercetools-sync-java#258]
### Description
create a dedicated util `mapValuesToFutureOfListCompletedValues` of of `mapValuesToFutureOfCompletedValues`

Check comments: https://github.com/commercetools/commercetools-sync-java/pull/254#discussion_r170242219, https://github.com/commercetools/commercetools-sync-java/pull/254#discussion_r170244793

**Comment by ahmetoz** [comment]
The issue should be managed/refactored as a boy-scout change next time when we are working on this utility next time, currently scope of the issue is not clear, therefore I'm closing it.
