### ISSUE TITLE
Update Java SDK version dependency

### ISSUE THREAD

**Issue by damarna85** [commercetools/commercetools-sync-java#262]
### Description
Basically since Java SDK 1.28 release there are a couple of breaking changes which are affecting this library (category draft mainly). Can you please update to the latest version of the SDK? Now is using the 1.27.0 but the 1.29.0 has already been released.

### Possible Solution
Update the dependency to the latest Java SDK release.

**Comment by heshamMassoud** [comment]
Hi @damarna85, thanks for opening the issue 🙂 The version is now updated and merged to master.

**Comment by damarna85** [comment]
Great thanks a lot @heshamMassoud ! Do you have any estimated date when this will be released? Looking forward to this 🏆

**Comment by heshamMassoud** [comment]
**v1.0.0-M11** is planned to be released tomorrow 🚀

**Comment by heshamMassoud** [comment]
released in v1.0.0-M11
