### ISSUE TITLE
Consider removing the ending in the name `UpdateAction` in action build utils

### ISSUE THREAD

**Issue by heshamMassoud** [commercetools/commercetools-sync-java#266]
### Description
Consider removing the ending in the name `UpdateAction` in action build utils for shorter namings.

For example: 

`buildSetAssetDescriptionUpdateAction` -> `buildSetAssetDescriptionAction`

**Comment by ahmetoz** [comment]
Update actions are public methods, naming it will be a breaking change, I am not seeing this task as something important. I'm closing it.
