### ISSUE TITLE
Re-factor buildUpdateActionsFromOptionals to use variable arguments list

### ISSUE THREAD

**Issue by andrii-kovalenko-ct** [commercetools/commercetools-sync-java#276]
Seems like all `buildUpdateActionsFromOptionals` usages always wraps to list set of optionals in-place.

It might have sense to overload `buildUpdateActionsFromOptionals` to accept not only list, but also variable arguments array.

Reference: https://github.com/commercetools/commercetools-sync-java/pull/275/files#r178802144

**Comment by heshamMassoud** [comment]
also refer to: https://github.com/commercetools/commercetools-sync-java/pull/275/files#r178804890
