### ISSUE TITLE
Unit test behaviour instead of actual outputs of bigger utils

### ISSUE THREAD

**Issue by heshamMassoud** [commercetools/commercetools-sync-java#292]
### Description

In the bigger utils like `ProductSyncUtils.buildActions` (and on similar utils across the lib) it makes sense to test the actual behaviour of the method (assert on whether the methods inside are actually called or not with the correct parameters) rather than test the actual output from the smaller methods. 

This will make the test easier to read, extend and maintain.

Refer to this comment for more info:
https://github.com/commercetools/commercetools-sync-java/pull/290#discussion_r204849969

**Comment by ahmetoz** [comment]
I would not know what to fix with this issue, so for me nothing to fix, I don't want to find and remove the test cases just because they are long to read, that kind of issue should be fixed during the review.
