### ISSUE TITLE
Add support for sync of custom types

### ISSUE THREAD

**Issue by butenkor** [commercetools/commercetools-sync-java#300]
Add support for import/sync of custom types: https://docs.commercetools.com/http-api-projects-types.html

**Comment by dirkpaschke** [comment]
And please include product types : https://docs.commercetools.com/http-api-projects-productTypes.html

**Comment by butenkor** [comment]
@dirkpaschke Product types are in progress already: https://github.com/commercetools/commercetools-sync-java/issues/286

**Comment by heshamMassoud** [comment]
Released in [1.0.0](https://github.com/commercetools/commercetools-sync-java/releases/tag/1.0.0)
