### ISSUE TITLE
[products] Allow to resolve product references (or sets of product references) gracefully

### ISSUE THREAD

**Issue by butenkor** [commercetools/commercetools-sync-java#310]
### Description
Current product sync would fail creation/update of a product if it references another product which does not exist in CTP but might be provided within upcoming batches. Also mentioned [here](https://github.com/commercetools/commercetools-sync-java/pull/167) and [here](https://github.com/commercetools/commercetools-sync-java/issues/219).

### Expected Behaviour
It should be able to create or update a product with references to other products which might be supplied in upcoming (or even current) batch(es).

### Context
The order of products in the feed can not be guaranteed by external systems/PIMs

### Possible Solution
Create a product without references and update it once references has been supplied.

**Comment by ahmetoz** [comment]
This is already a feature: 
https://github.com/commercetools/commercetools-sync-java/blob/master/docs/usage/PRODUCT_SYNC.md#persistence-of-productdrafts-with-irresolvable-references
