### ISSUE TITLE
Rename parameters "newProductVariant" and "oldProductVariant" 

### ISSUE THREAD

**Issue by ahalberkamp** [commercetools/commercetools-sync-java#314]
### Description
The parameters "newProductVariant" and "oldProductVariant" should be renamed  to "sourceProductVariant" and "targetProductVariant ". So it`s   much more straight foreward to old and New.
 But now this (old and new) is used as a convention across the whole library and is not so easy to do without wasting some time.

**Comment by butenkor** [comment]
Why? Suggested naming implies a sync between 2 CTP projects: source and target. Previous naming seems to be more neutral, shorter and easier to understand if data is also supplied by any other external system.

**Comment by heshamMassoud** [comment]
@butenkor Why do you think it only implies a sync between 2 CTP projects? also when syncing from an external feed it's also considered as source and target. 

In my opinion, it's easier to understand when source and target - you don't think twice about it. You know what it means right away. However, when it is old and new, one could think hmm, is the target old or new, then it's confusing. But that's just my opinion.

**Comment by heshamMassoud** [comment]
related to https://github.com/commercetools/commercetools-sync-java/issues/176

**Comment by ahalberkamp** [comment]
We are using the old/new pattern everywhere else in the productsync , so is make no sense to do the renaming for product variants
