### ISSUE TITLE
Add unit tests for ProductType sync

### ISSUE THREAD

**Issue by heshamMassoud** [commercetools/commercetools-sync-java#329]
### Description

As a consequence of this [discussion](https://github.com/commercetools/commercetools-sync-java/pull/316/files#r230400471), the productType sync module should also be covered by unit tests.

**Comment by heshamMassoud** [comment]
Also refer to https://github.com/commercetools/commercetools-sync-java/issues/302

**Comment by ahmetoz** [comment]
Currently, we have test cases for the product types, https://github.com/commercetools/commercetools-sync-java/blob/master/src/test/java/com/commercetools/sync/producttypes/ProductTypeSyncTest.java
