### ISSUE TITLE
DuplicateKeyException and DuplicateNameException should be checked exceptions.

### ISSUE THREAD

**Issue by heshamMassoud** [commercetools/commercetools-sync-java#330]
### Description
`DuplicateKeyException` and `DuplicateNameException` should be checked exceptions. Since they don't represent an error in the code but an exception of invalid input data.

**Comment by ahmetoz** [comment]
According to the code, those exceptions are already a checked exception, but handled as below, which looks ok as a callback.

https://github.com/commercetools/commercetools-sync-java/blob/385aa402e520ffa37b0e3b072cfdc25f106755a2/src/main/java/com/commercetools/sync/types/utils/TypeUpdateActionUtils.java#L96-L100
