### ISSUE TITLE
The `syncBatches` method implementation could be moved to the `BaseSync` class.

### ISSUE THREAD

**Issue by valdemon** [commercetools/commercetools-sync-java#334]
### Description

It might have sense to move the implementation of the [BaseSync.syncBatches](https://github.com/commercetools/commercetools-sync-java/blob/master/src/main/java/com/commercetools/sync/commons/BaseSync.java#L86) method to the `BaseSync` class (reusing generics) as the implementation is currently functionally identical in every of its subclass ones, unless there is a good reason to keep the current state.

### Possible Solution

Will come with a PR.

**Comment by heshamMassoud** [comment]
Hey @valdemon, thanks for the clean up. But we only close issues when they are released so the users don't expect closed issue/feature/bugfix to be in a release that they are using for example 😉

**Comment by heshamMassoud** [comment]
released in [1.0.0](https://github.com/commercetools/commercetools-sync-java/releases/tag/1.0.0)
