### ISSUE TITLE
Make stricter PMD rule priority (if it makes sense)

### ISSUE THREAD

**Issue by heshamMassoud** [commercetools/commercetools-sync-java#34]
### Description
The current PMD rule priority 2 could be very liberal. Might make sense to make it more strict.

### Current Behaviour
Currently PMD rule priority is set to [2](https://github.com/commercetools/commercetools-sync-java/blob/master/gradle-scripts/pmd.gradle#L8).

### Expected Behaviour
Make the rule more stricter if it makes sense.

**Comment by LEQADA** [comment]
@heshamMassoud I think it is not only about changing priority. On priority set to 3 PMD reports a lot of falls positives. So they are all should be handled separately as a configuration. The question is do we really need that. 
I would say it is good to fix what is fixable and keep the priority as it is.
What do you think?

**Comment by heshamMassoud** [comment]
@LEQADA Could you please give examples of the false positives? If you increase the priority and you get false positives and as well as true positives. Then it would make sense to:-
1. Increase the priority.
2. Change the configuration to not give an error on the false positives.
3. Fix the code that gives the true positives so that PMD doesn't complain with such rule priority.

That's my opinion, we would need that so we don't have the true positives :)

WDYT?

> I would say it is good to fix what is fixable and keep the priority as it is.

Not sure what you mean here. Right now, there is nothing to fix because there are no errors with such priority.

**Comment by ahmetoz** [comment]
closed with #652
