### ISSUE TITLE
Refactor CategorySync class

### ISSUE THREAD

**Issue by heshamMassoud** [commercetools/commercetools-sync-java#343]
Check the comment here: https://github.com/commercetools/commercetools-sync-java/pull/340#discussion_r237840012

I agree this lambda got huge now. I split it now into smaller methods:

1a7e92c

I saw already more space for refactoring/improvement: (I don't like keeping state of the collections and mutating them in different methods, also moving the assignment of `categoryKeysToFetch` in the method `prepareDraftsForProcessing`, etc..)

**Comment by ahmetoz** [comment]
CategorySync will be refactored soon to implement the unresolved references. Hereby I'm closing this ticket because it will be outdated.
