### ISSUE TITLE
Improve error message of productType without key

### ISSUE THREAD

**Issue by heshamMassoud** [commercetools/commercetools-sync-java#371]
### Description
Improve error message of productType without key.

### Current Behaviour

If a productType has no key, the message given to the error callback is:

```java
"Failed to process product type draft without key."
```

### Expected Behaviour
The message should contain something that the user can identify which product type is that for easier fixing. For example: name.

**Comment by ahmetoz** [comment]
We are adding name of the product type into the error callback message: 

https://github.com/commercetools/commercetools-sync-java/blob/ff8a981a307d975da6326dea47e166c24d6e6ecc/src/main/java/com/commercetools/sync/producttypes/helpers/ProductTypeBatchValidator.java#L31-L32
