### ISSUE TITLE
`BaseSyncStatistics::getLatestBatchHumanReadableProcessingTime` not giving the proper results

### ISSUE THREAD

**Issue by ahmetoz** [commercetools/commercetools-sync-java#378]
### Description

`BaseSyncStatistics::getLatestBatchHumanReadableProcessingTime` not giving the proper results..

This issue reported as this : 
> `BaseSyncStatistics::getLatestBatchHumanReadableProcessingTime` consistently gives me values like `"0d, 0h, 0m, 3223s, 223ms”

### Possible Solution

https://github.com/commercetools/commercetools-sync-java/blob/master/src/main/java/com/commercetools/sync/commons/helpers/BaseSyncStatistics.java#L183 calculation of minutes looks like a typo, should be calculated from `latestBatchProcessingTimeInMillis`

**Comment by heshamMassoud** [comment]
Shipped with release [`1.3.0`](https://github.com/commercetools/commercetools-sync-java/releases/tag/1.3.0)
