### ISSUE TITLE
Add support for sync of cart discounts

### ISSUE THREAD

**Issue by butenkor** [commercetools/commercetools-sync-java#379]
Allow to import/sync cart discounts. As there is no cart discount key available from API yet we should use cart discount key defined as custom fields. 
Note: Check current state of API development (CTP-1913) to check if native keys will be available soon.

**Comment by heshamMassoud** [comment]
Shipped with release [`1.3.0`](https://github.com/commercetools/commercetools-sync-java/releases/tag/1.3.0)
