### ISSUE TITLE
null CategoryDrafts are not counted as `processed`

### ISSUE THREAD

**Issue by heshamMassoud** [commercetools/commercetools-sync-java#39]
#### Current Behaviour
Currently, if one of the input CategoryDrafts is `null` it won't be counted as `processed`.

This can be found here: https://github.com/commercetools/commercetools-sync-java/blob/develop/src/main/java/com/commercetools/sync/categories/CategorySync.java#L81-L82

#### Expected Behaviour
It, however, should be counted as `processed`. 

#### Proposed Solution
Either count it as `failed` or have a new counter `invalidResource`.

**Comment by heshamMassoud** [comment]
@jakubchrobak Please make sure the inventory sync also handles this.

**Comment by butenkor** [comment]
The idea is that summary report on: `sync([cat1,null,cat2,cat3,cat5])` looks like that:
```
{"processed": 5, "created": 2, "updated": 2, "failed": 1}
```
