### ISSUE TITLE
Sync States

### ISSUE THREAD

**Issue by jarzynp** [commercetools/commercetools-sync-java#409]
### Description
Provide synchronization of states (https://docs.commercetools.com/http-api-projects-states)

### Current Behaviour
Not existing

### Expected Behaviour
To be able to use library to sync those assets

### Additional information
Because there are already existing StateServiceImpl and TaxCategoryServiceImpl they will have to be renamed because they are product-specific not general ones.

Will come with PR.

**Comment by heshamMassoud** [comment]
HI @jarzynp we are looking foreward for your PRs :)

Just thought maybe this might help -> Right now we're in the process of finishing up a PR for [CartDiscount Sync](https://github.com/commercetools/commercetools-sync-java/pull/408). You can find there all the things we tend to include when adding a new sync module, this could help you when adding the 2 new sync modules.

Cheers!

**Comment by jarzynp** [comment]
Hi

PR ready: [#415](https://github.com/commercetools/commercetools-sync-java/pull/415)

I've added some notes to be aware of while doing review.

Enjoy ;)

**Comment by ahmetoz** [comment]
Released with version 1.9.0
