### ISSUE TITLE
Consider using JUnit 5

### ISSUE THREAD

**Issue by heshamMassoud** [commercetools/commercetools-sync-java#41]
### Description

Consider using JUnit 5 instead of AssertJ as it will have most of the features that are needed but missing in JUnit 4. However, JUnit 5 is still an RC, nevertheless a [GA is planned to be released on Q3 2017](https://github.com/junit-team/junit5/wiki/Roadmap#phase-7-ga-release). 

As a developer, I want to Bump to JUnit 4 to JUnit 5, so that the Java Sync uses only 1 Testing dependency.

### Expected Behavior
After using Junit 5, AssertJ won't be needed.

### Current Behavior
Currently AssertJ is used for easier unit testing with it's API, for example:
````
 assertThatThrownBy(() -> { throw new Exception("boom!"); }).isInstanceOf(Exception.class)
                                                             .hasMessageContaining("boom");
}
````
which is not in Junit 4, but will be in 5.

**Comment by ahmetoz** [comment]
Maybe in a different library, we could try that but for now, we don't know how to migrate all our assertions to JUnit 5 equivalents, also there is no business value or benefit of this issue. So I am closing the task.
