### ISSUE TITLE
ClientConfigurationUtils#createClient works in a misleading way

### ISSUE THREAD

**Issue by jakubchrobak** [commercetools/commercetools-sync-java#42]
### Description
I ran into this problem when I try to sync 2 projects during integration tests. I've created 2 `CtpClient` instances for source and target projects, by providing different `SphereClientConfig` to constructor. During supply data to CTP, using `BlockingSphereClient` instances from createad  `CtpClient` instances, I got an error that I try to create a resource that already exists. After research it turned out, that both `CtpClient` instances contain the same `BlockingSphereClient` instance. `CtpClient`constructor use `ClientConfigurationUtils#createClient` that creates sphere client only during first call, and then returns cached instance during next calls. Cached client is returned regardless if passed `SphereClientConfig` is the same as for first call or not.

### Expected Behavior
`ClientConfigurationUtils#createClient` should return different `BlockingSphereClient` instances for creation request for different `SphereClientConfig` instances passed.
````
// Having not equal config1, config2 instances of SphereClientConfig
// When
BlockingSphereClient client1 = ClientConfigurationUtils createClient(config1);
BlockingSphereClient client2 = ClientConfigurationUtils createClient(config2);
//Then
client1.equals(client2) == false
````

### Current Behavior
When `ClientConfigurationUtils#createClient` initialize `BlockingSphereClient` once, and then return same instance for every creation request.
````
// Having not equal config1, config2 instances of SphereClientConfig
// When
BlockingSphereClient client1 = ClientConfigurationUtils createClient(config1);
BlockingSphereClient client2 = ClientConfigurationUtils createClient(config2);
//Then
client1.equals(client2) == true
````

### Context
It would be common situation for user of a module to sync 2 different projects. That is why he should obtain proper sphere client when he use `CtpClient` or `ClientConfigurationUtils`

### Possible Solution
In `ClientConfigurationUtils` use `Map` for caching where key is `SphereClientConfig` and value is `BlockingSphereClient` instance

**Comment by heshamMassoud** [comment]
You are right. It's definitely not correct to have the BlockingSphereClient as a static attribute. The CtpClient is useless in this case.

**Comment by butenkor** [comment]
I wonder why do you need both helper classes (ClientConfigurationUtils.java, helpers/CtpClient.java) at all if client is created and passed by the sync caller?

**Comment by heshamMassoud** [comment]
@butenkor the main idea of `CtpClient`is to wrap the `SphereClientConfig` and the `BlockingSphereClient` together. This brings the advantage of simplifying the options builders by having the client building code in this `CtpClient`, instead of having it in all the subclasses of `BaseSyncOptionsBuilder`.

**Comment by heshamMassoud** [comment]
@butenkor https://github.com/commercetools/commercetools-sync-java/tree/master/src/main/java/com/commercetools/sync/categories#ctpclient-required this is how the user will pass it.

**Comment by heshamMassoud** [comment]
Also to document here since we discussed it in words, because the project key is not accessible through the client only. So the user would need to pass the config as well. 

I created an issue to on JVM SDK to be able to access it: https://github.com/commercetools/commercetools-jvm-sdk/issues/1403

**Comment by jakubchrobak** [comment]
Resolved with PR https://github.com/commercetools/commercetools-sync-java/pull/43
