### ISSUE TITLE
Filter null value for custom field update actions

### ISSUE THREAD

**Issue by JudeNiroshan** [commercetools/commercetools-sync-java#428]
### Description
I want to be able to set null for custom price field attribute value: 
1. Set null as value without failures
2. Should not generate 2 update actions when new value is null
...
so that:
1. sync-java will create only remove update action as the value is null
2. should not fail the sync process because of trying to update resource which do not exists

### Current Behaviour

When there is a custom field for price with null as the value in a given draft, sync-java will generate 2 remove update actions on this scenario. It leads to the error from platform of "trying to remove an attribute which does not exists"

````bash
newCustomFields.keySet().stream()
                              .filter(newCustomFieldName -> !Objects.equals(newCustomFields.get(newCustomFieldName),
                                  oldCustomFields.get(newCustomFieldName)))
````

### Expected Behaviour

Should only generate 1 update action to remove the custom field attribute.
### Context

When trying to sync a value set as null from the platform, then try to use sync-java to synchronize data with other CTP project.
### Possible Solution
````bash
<!-- Not obligatory, but suggestions or ideas are always welcome. -->
newCustomFields.keySet().stream()
                              .filter(newCustomFieldName -> Objects.nonNull(newCustomFields.get(newCustomFieldName)))
                              .filter(newCustomFieldName -> !Objects.equals(newCustomFields.get(newCustomFieldName),
                                  oldCustomFields.get(newCustomFieldName)))
````

**Comment by heshamMassoud** [comment]
released in [1.4.1](https://commercetools.github.io/commercetools-sync-java/doc/RELEASE_NOTES/#141-sept-2-2019).
