### ISSUE TITLE
Update jvm-sdk to v1.46.0 which includes update actions for setting custom fields to accept empty array values

### ISSUE THREAD

**Issue by JudeNiroshan** [commercetools/commercetools-sync-java#430]
### Description

As a sync-java user, 
I want: 
1. set empty array as a custom field value in the source project and run the sync process without failures
...
so that:
1. target project also has the empty array values for custom fields

### Current Behaviour

If the source project has a custom field for price with empty array as the value, after the running the sync-java, in the target project completely removed the custom field.

It should not remove the custom field in the target project.

````bash

````

### Expected Behaviour

When the source project has a product variant with custom price field that has an empty array as the value, target project should also has the empty array as the value for the custom price field.
### Context

This caused for the error from platform indicating that "trying to modify an attribute which does not exists". Because in the target project, instead of empty array, sync-java removes the attribute.
### Possible Solution

Found the problem is because the jvm-sdk has excluded the empty arrays as the value for price custom fields. This has been fixed in the jvm-sdk. So, we need to update our dependency to jvm-sdk v1.46.0

https://github.com/commercetools/commercetools-jvm-sdk/releases/tag/v1.46.0

**Comment by JudeNiroshan** [comment]
https://github.com/commercetools/commercetools-sync-java/pull/431

**Comment by heshamMassoud** [comment]
Hi @JudeNiroshan  we only close issues when the fix they address is already released. We use the label `merged-to-master` for fixes which are merged to master but not released yet. Therefore, I'll reopen this one.

**Comment by heshamMassoud** [comment]
released in [1.4.1](https://commercetools.github.io/commercetools-sync-java/doc/RELEASE_NOTES/#141-sept-2-2019).
