### ISSUE TITLE
Bug on FasterXML/jackson-databind on arrayNode adding null values.

### ISSUE THREAD

**Issue by heshamMassoud** [commercetools/commercetools-sync-java#441]
### Description
The test `resolveAttributeReference_WithNullReferenceInSetAttribute_ShouldResolveReferences` is `disabled` due to a possible bug on FasterXML/jackson-databind#2442. 

This was added in this PR: https://github.com/commercetools/commercetools-sync-java/pull/439

It should be investigated whether we should handle this bug on the library or wait for fix while documenting it's consequences on the library's usage.

**Comment by cowtowncoder** [comment]
Fix was included in Jackson `2.10.0` release which is now available.

**Comment by heshamMassoud** [comment]
Great news! @cowtowncoder thanks

**Comment by cowtowncoder** [comment]
Thank you for your help, was a good fix!

**Comment by heshamMassoud** [comment]
released in https://github.com/commercetools/commercetools-sync-java/releases/tag/1.6.1
