### ISSUE TITLE
Sync products in any order even if they have self-references

### ISSUE THREAD

**Issue by heshamMassoud** [commercetools/commercetools-sync-java#447]
Since a productDraft X could be supplied in with an attribute referencing productDraft Y. It could be that Y is not supplied before X, which means the sync could fail creating/updating X. It could also be that Y is not supplied at all in this batch but at a later batch.

The product sync would fail updating/creating this draft immediately, since the reference resolver component would fail to resolve such reference since it does not exist (yet). However, the library should keep track of such "referencing" drafts like X and persist them in storage (CTP customObjects in this case) to keep them and create/update them accordingly when the references are there.

**Comment by lojzatran** [comment]
Description for the issue is missing @heshamMassoud

**Comment by heshamMassoud** [comment]
> Description for the issue is missing @heshamMassoud

now it's not 😛

**Comment by heshamMassoud** [comment]
released in https://github.com/commercetools/commercetools-sync-java/releases/tag/1.6.0
