### ISSUE TITLE
CompletableFuture.allOf does not limit max concurrency

### ISSUE THREAD

**Issue by lojzatran** [commercetools/commercetools-sync-java#48]
### Description
`CompletableFuture.allOf` does not restrict how many concurrent requests it will create. If you have batch of 1000 inventories, it can create 1000 requests at once. This can put a big pressure on the platform. Please find a way how to define max number of parallel threads (requests) that can be run at once.

**Comment by butenkor** [comment]
I think we should document how users shall create clients before they pass it the syncers. For example they should always use [QueueSphereClientDecorator](https://github.com/commercetools/commercetools-jvm-sdk/blob/b3768bec927e9d38c500e7e57198cc53faf7dc81/commercetools-java-client-core/src/test/java/io/sphere/sdk/client/QueueSphereClientDecoratorTest.java#L26). I think task queue should always be used by default following [issue](https://github.com/commercetools/commercetools-jvm-sdk/issues/1405) has been also create for SDK.

**Comment by jakubchrobak** [comment]
I mentioned this in the [README](https://github.com/commercetools/commercetools-sync-java/tree/master/src/main/java/com/commercetools/sync/inventories#sync-list-of-inventory-entry-drafts) documentation and provided the showcase integration tests.

**Comment by heshamMassoud** [comment]
Mentioned in point 3 [here](https://github.com/commercetools/commercetools-sync-java/tree/master/src/main/java/com/commercetools/sync/categories#prerequisites)
