### ISSUE TITLE
Improve document about integration test

### ISSUE THREAD

**Issue by leungkinghin** [commercetools/commercetools-sync-java#506]
### Description
Missing paragraph to tell developers how to fill the credential information in case they have to run integration test locally.

### Suggestion
Add supplementary document to describe the procedure how to create sample source/target project in merchant center, and obtain the credential information.

**Comment by JudeNiroshan** [comment]
@leungkinghin I see this existing doc page covers what you have mentioned in this issue. Isn't it? https://github.com/commercetools/commercetools-sync-java/blob/master/docs/CONTRIBUTING.md

**Comment by leungkinghin** [comment]
> @leungkinghin I see this existing doc page covers what you have mentioned in this issue. Isn't it? https://github.com/commercetools/commercetools-sync-java/blob/master/docs/CONTRIBUTING.md

I think it would be a bit better to direct developers to following link so that they can obtain the credentials for it.properties.
https://docs.commercetools.com/merchant-center/projects.html
Indeed no long paragraph or document is needed.
