### ISSUE TITLE
Artifacts for v1.8.1 are not published

### ISSUE THREAD

**Issue by htimur** [commercetools/commercetools-sync-java#512]
**Describe the bug**
I see that version 1.8.1 was released but they are not published to Maven Central or Bintray. It would be good to have them, as we are currently facing conflicts with the previous version due to the outdated SDK version.

**To Reproduce**
Update version of the sync library to 1.8.1 and try to build the project

**Expected behavior**
The library should be downloaded from the public repository of choice

**Comment by ahmetoz** [comment]
Hi @htimur, Thanks for letting us know. Yes, that’s correct. We already know the problem and we are working on it. We are having issues currently with the bintray tool and will come up with a solution asap and let you know.

**Comment by ahmetoz** [comment]
For a quick update, the library is published now to the jcenter/bintray, I am checking the problem on the maven central.

**Comment by htimur** [comment]
Hi @ahmetoz, thank you for the quick update. We update our dependencies and get back to you.

**Comment by ahmetoz** [comment]
Now, maven central is also could be used. I am closing the issue.
