### ISSUE TITLE
Propagate main resources to all callbacks

### ISSUE THREAD

**Issue by lojzatran** [commercetools/commercetools-sync-java#522]
**Describe the bug**
See discussion: https://github.com/commercetools/commercetools-sync-java/pull/367/files?file-filters%5B%5D=.java#r280379464

**Problem explanation**
In Product sync we also sync its references like Assets. It means that Assets are part of Product. In java-sync ProductVariantUpdateActionUtils.java:buildProductVariantAssetsUpdateActions() we use ProductSyncOptions.applyErrorCallback(oldResource: Product, newResourceDraft: ProductDraft), but in the method, we don't have Product resources available. In this case the callback will not receive any resources and then our change will be useless. This error also leads to a weird construct like in the link above where you have to compare Class types of generics etc.

**Expected behavior**
Solution: As suggested, we should rather propagate Product and ProductDraft to the error callbacks, and not passing only a references in case of error.

**Comment by ahmetoz** [comment]
Released with: https://github.com/commercetools/commercetools-sync-java/blob/master/docs/RELEASE_NOTES.md#200---sept-14-2020
