### ISSUE TITLE
Product does not get published if it was published already

### ISSUE THREAD

**Issue by butenkor** [commercetools/commercetools-sync-java#530]
**Describe the bug**
If a new product draft has a `publish` flag set to `true` and the existing product is published already then no publish action will be created.

**To Reproduce**
1. Create a product and publish it
2. Supply new draft with `publish` flag set to `true` and changed product name
3. As a result, a product will be updated with a new name but changes will not be published right away

**Expected behavior**
Should publish a product even if it was published before.

**Additional context**
Calculate at the end of comparison a publish action: https://github.com/commercetools/commercetools-sync-java/blob/b7630115ac9576b063b879dc17d05b08af86b200/src/main/java/com/commercetools/sync/products/utils/ProductSyncUtils.java#L115

Util to create update publish/unpublish actions: https://github.com/commercetools/commercetools-sync-java/blob/b7630115ac9576b063b879dc17d05b08af86b200/src/main/java/com/commercetools/sync/products/utils/ProductUpdateActionUtils.java#L530

Here is the issue as this util is not suitable for the publishing process but a calculation of other product changes only. Here both the new draft as also existing product have value `true` which as a result will produce no update action: 
https://github.com/commercetools/commercetools-sync-java/blob/b7630115ac9576b063b879dc17d05b08af86b200/src/main/java/com/commercetools/sync/commons/utils/CommonTypeUpdateActionUtils.java#L33

New mapping:
| New draft publish | Old product publish | New update actions | Old product hasStagedChanges | Action
|:-:|:-:|:-:|:-:|:-:|
| false | false | false | false | - |
| false | false | false | true | - |
| false | false | true | false | - |
| false | false | true | true | - |
| false | true | false | false | unpublish |
| false | true | false | true | unpublish |
| false | true | true | false | unpublish |
| false | true | true | true | unpublish |
| true | false | false | false | publish |
| true | false | false | true | publish |
| true | false | true | false | publish |
| true | false | true | true | publish |
| true | true | false | false | - |
| true | true | false | true | publish |
| true | true | true | false | publish |
| true | true | true | true | publish |

**Comment by ahmetoz** [comment]
Released with version 1.9.1
https://github.com/commercetools/commercetools-sync-java/blob/master/docs/RELEASE_NOTES.md#191----aug-5-2020
