### ISSUE TITLE
Re-factor BaseSync#process CompletionStages as it designed by Java

### ISSUE THREAD

**Issue by andrii-kovalenko-ct** [commercetools/commercetools-sync-java#65]
### Description

In current implementation of `CategorySync#process()` and `ProductSync#process()`:
  1. Completion stages are blocked on every iteration (`.toCompletableFuture().get()`)

  2. Providing executor (thread pool) is not possible to use Async operation.

### Solution

  - [ ] See `InventorySync#createMissingSupplyChannels()` and `InventorySync#splitToBatchesAndProcess`: they use `CompletableFuture#allOf()` to complete batch of completion stages.

  - [ ] inject `java.util.concurrent.Executor` to sync classes as an optional value and use in in completion stage operations. Otherwise use default executor.

**Comment by ahmetoz** [comment]
That issue does not look up to date, we are using the best practice on the processing batches, probably implementation is changed after this task, and we have not managed the open issue for it.
