### ISSUE TITLE
Share common code style scheme

### ISSUE THREAD

**Issue by ghost** [commercetools/commercetools-sync-java#66]
### Description
It's just a proposition. It could be convenient if a common IntelliJ [code style scheme](https://www.jetbrains.com/help/idea/code-style.html) was shared via github repository. Then every developer could import it to the project in his IDE, what makes the reformatting of a code consistent among all contributors.

### Expected Behaviour
Code commited by every developer is formatted according to the same set of rules.

### Current Behaviour
Reformatting code leads to a subtle differences (e.g. not consistent indentation). 

### Context
"Wrong format" reviews would disappear from pull requests.

**Comment by ahmetoz** [comment]
Instead of sharing a common schema, we need to use auto code formatted. #293. I am closing the issue.
