### ISSUE TITLE
Consider Reactive Programming Model (RxJava) + other refactoring points

### ISSUE THREAD

**Issue by piobra** [commercetools/commercetools-sync-java#68]
### Problem
There are following basic concerns in the library:
* executing sync
* handling errors
* gathering statistics
* parallel processing

Problems that exist in the code:
* mixed logic of the concerns above
* very tight coupling between them

### Solution
IMHO we should apply some kind of observer pattern implementation here that
would really make coupling a lot more loose and provide means of separation.

And as library is getting more and more complex I'd take it under serious consideration if we should not do it with some reactive library, like https://github.com/ReactiveX/RxJava as it already provides solutions for event-driven async programming (actually strongly related to listener-observer).
It's easier to implement a resilient architecture using this framework. It also provides means of pararell stream processing which is IMO ideal for sync library.

### Other refactoring points
1) BaseSync -> sync invokes process from derived class makes the code obfuscated
suggestion -> use delegation istead of inheritance
the same with statistics - there is already a getter for it
2) services are created inside sync classes - increases coupling
service should be created by external factory and provided as a dependency
3) statistics should be implemented on listener fashion, they should react on some event
4) consider making util sync classes hidden by interfaces to loosen coupling and improve testability
created as singleton provided by factory
hide implementation details not needed to be known by library's client
5) tests - use json mock data resources
6) tests - use commercetools-test-lib
9) in SyncOptionsBuilder-s a convention of setters naming should follow naming without 'set' prefix
as it's usually done in fluent builders
10) a builder should list its required parameters inside constructor
11) get rid of getThis method in builders

**Comment by ahmetoz** [comment]
Could not see any benefit of this task, RxJava or reactive programming could make sense if we handle the data streaming but its part of the client of the library, we are doing the async with java's builtin features (completable future), the client can map future to RX java or reactor equivalent and can use it as their wish. 
Another reason development effort vs business benefit is not clear from this issue, not sure maybe it was easy to migrate before.. Hereby I am closing this issue.
