### ISSUE TITLE
description field in Categories setDescription update action is optional

### ISSUE THREAD

**Issue by heshamMassoud** [commercetools/commercetools-sync-java#71]
### Description
In CTP, categories SetDescription Update action doesn't require the description field to be set. In other words, it allows unsetting the description.  See: https://github.com/commercetools/commercetools-jvm-sdk/issues/1454

Currently, the sync library will trigger the error callback if the user tried to unset the description field. This validation should be removed.

**Comment by butenkor** [comment]
Any details on the issue?

**Comment by heshamMassoud** [comment]
@butenkor thx, forgot to update it. Now added.

**Comment by heshamMassoud** [comment]
addressed by 3061867b20ab82bcd20729e1d587772d8783895b
