### ISSUE TITLE
[Hacktoberfest] Migrate deprecated test assertions to resolve warnings.

### ISSUE THREAD

**Issue by ahmetoz** [commercetools/commercetools-sync-java#769]
**Situation:**

We have warnings on compile.

**Complication:**

It's not blocking the build but it's nice to fix the warnings to avoid future problems.
Most of the errors are related to using deprecated methods.

**Resolution:**
Migrate deprecated test assertions to resolve warnings.

**Solution ideas:**

1- hasOnlyOneElementSatisfying is deprecated, we need to use singleElement()

```
warning: [deprecation] hasOnlyOneElementSatisfying(Consumer<? super ELEMENT>) in AbstractIterableAssert has been deprecated
            .hasOnlyOneElementSatisfying(throwable -> {
            ^
```

For example:
````java
assertThat(errorMessages)
            .hasSize(1)
            .hasOnlyOneElementSatisfying(message -> {
                assertThat(message).contains("Failed to create draft with key: 'productKey'.");
                assertThat(message).contains("BadRequestException");
            });
````
to
````java
assertThat(errorMessages)
            .hasSize(1)
            .singleElement(as(STRING))
            .contains("Failed to create draft with key: 'productKey'.")
            .contains("BadRequestException");
````

second example:
````java
 assertThat(errorCallBackExceptions).hasOnlyOneElementSatisfying(throwable -> {
            assertThat(throwable).isInstanceOf(SyncException.class);
            assertThat(throwable).hasMessage(PRODUCT_TYPE_DRAFT_IS_NULL);
        });
````

to 

````java

        assertThat(errorCallBackExceptions).singleElement()
                                           .withFailMessage(PRODUCT_TYPE_DRAFT_IS_NULL)
                                           .isInstanceOf(SyncException.class);
````

-----
[CONTRIBUTING](https://github.com/commercetools/commercetools-sync-java/blob/master/docs/CONTRIBUTING.md), [CODE_OF_CONDUCT](https://github.com/commercetools/commercetools-sync-java/blob/master/docs/CODE_OF_CONDUCT.md)

**Comment by pedro-cze** [comment]
Hi @ahmetoz, I'd like to work on this issue, if it's not taken.

**Comment by ahmetoz** [comment]
Hey @pedro-cze feel free to contribute, thanks! Let us know when you need help ^^
