### ISSUE TITLE
Consider removing category key from CategoriesWithMissingParents on any failure

### ISSUE THREAD

**Issue by heshamMassoud** [commercetools/commercetools-sync-java#77]
Consider removing category key from CategoriesWithMissingParents on any failure (like creation failure or update failure). Might not be needed. But definitely needs considering.

**Comment by butenkor** [comment]
Why? Should not this be part of statistics with info of CategoriesWithMissingParents which could not be resolved?

**Comment by heshamMassoud** [comment]
@butenkor the sync checks at first for missing parents in the input list of drafts, and accordingly it adds the keys of the ones with missing parents to `CategoriesWithMissingParents` map. Then it does the actual create/update on the category. However, what if, it failed to create/update. We would still have the category key in the `CategoriesWithMissingParents` map, even though it failed to create/update.

**Comment by butenkor** [comment]
Which is expected as in the end you want to provide an info on total amount of unresolved categories and which are those. Unresolved means:
- could not be created as was never supplied
- create request failed (of course it should retry)

**Comment by heshamMassoud** [comment]
No, I think you didn't get what I mean. Let's say you have a batch of 1 categoryDraft input to the sync:
 ````JSON
 ["cat1"]
````
This categoryDraft has in its parent field `"cat2"`. However, `"cat2"` still doesn't exist. So the sync will first update the `CategoriesWithMissingParents `. So it will be 
````JSON
"cat2" -> ["cat1"]
````
Then the sync would attempt to create `"cat1"`, then it fails and _retries_ according to the retry strategy. And let's say eventually would fail by the end after all retries. 

Now the problem is `CategoriesWithMissingParents ` would still have the key of "cat1" which doesn't even exist (because it failed to create). 

Thats's what I meant by this issue.

**Comment by ahmetoz** [comment]
We need to get rid of using memory for handling unresolved references, we need to refactor all category-sync to use a custom-object for persisting un-resolved references instead of using statistic object (similar to product-sync), hereby I am closing this issue, we will plan this refactoring soon.
