### ISSUE TITLE
[Hacktoberfest] Fix the javadoc badge in readme.

### ISSUE THREAD

**Issue by ahmetoz** [commercetools/commercetools-sync-java#770]
**Situation**
We are using badges to show links and updates of the repository. The badge to show javadoc updates is not working anymore.

**Complication**
It's confusing for users of the library to see an invalid badge, seems the javadoc-badge is not working anymore,
http://javadoc-badge.appspot.com/com.commercetools/commercetools-sync-java.svg?label=Javadoc

<img width="775" alt="Screenshot 2021-09-24 at 09 57 46" src="https://user-images.githubusercontent.com/3469524/134639497-46f0f32f-4932-4e85-8eaa-b1b3d8bb7159.png">

**Resolution**
Fix the javadoc badge in readme.

Please check the other readme too: https://github.com/commercetools/commercetools-sync-java/blob/master/docs/README.md

[CONTRIBUTING](https://github.com/commercetools/commercetools-sync-java/blob/master/docs/CONTRIBUTING.md), [CODE_OF_CONDUCT](https://github.com/commercetools/commercetools-sync-java/blob/master/docs/CODE_OF_CONDUCT.md)

**Comment by priyamm** [comment]
Okay fixing this issue.
