### ISSUE TITLE
Update actions can't be unset by CTP

### ISSUE THREAD

**Issue by heshamMassoud** [commercetools/commercetools-sync-java#8]
`buildSetDescriptionUpdateAction`, `buildChangeParentUpdateAction` and `buildChangeOrderHintUpdateAction` methods don't handle unsetting the description, parent and orderhint if they weren't set in the category draft because the API has their values required in the update action payload. 

A ticket was raised on the help desk [here](https://sphere.atlassian.net/servicedesk/customer/portal/1/SUPTEST-299)

**Comment by nkuehn** [comment]
@heshamMassoud  the helpdesk link is only for you - not possible to access it. 

I would never wait for platform changes.  This is just one example of things that cannot be changed in the platform once set - there are many many of them. 

So to me the interesting question is just:  is it a warning or a fatal error if the change to the new data provided is not possible?

**Comment by heshamMassoud** [comment]
@nkuehn ah ok, probably then would remove the help desk url (since this repo will be open). 

Regarding, how it's currently handled (as a work around with TODO in code until fixed by CTP); If any of these new values (`description`, `parent` or `orderHint`) are unset, simply an update action will not be not be created at all (as discussed with @butenkor).

Still not sure whether it should be warning or fatal error.

**Comment by nkuehn** [comment]
I think it's an ERROR, but not fatal.   
It's a source data bug just like e.g. missing required fields.

**Comment by heshamMassoud** [comment]
@nkuehn But actually IMO, I don't think it's a source data bug because what if someone wants to remove the `description`/`parent`/`orderHint` from a category?

When creating a JVM SDK `CategoryDraft` these fields are not required. They are only required when issuing an update action for them. So for me it feels more of a missing feature in our API.

**Comment by nkuehn** [comment]
Do you want to make yourself dependent on at least 10-20 platform changes to get this library out?   
You can choose to,  estimated arrival 2019-2020. 

Sorry, you have to find a definition how to handle the cases and not a definition of what in gerneral globally would be the correct final end result.

**Comment by heshamMassoud** [comment]
Handeling the issue temporary until the platform is changed is one thing and how the correct behaviour should be is another thing. The latter is why this issue is here, as a reminder for the future.

As I said, currently right now it is handled to not do an update action when the fields are not set. So this library is not gonna be waiting/dependant on the platform change. An ERROR, as you mentioned, would be then thrown from the sync module that the fields are missing. 

Regarding the current behaviour of the platform, so It's currently not possible to remove a parent/description/orderHint of a category? (only by deleting the category and creating it again without those fields), right?

**Comment by butenkor** [comment]
For now i would not throw any error and i would not even log anything as it does not change current data in any way and initially is not mandatory. Lets keep logs clean from begin on :)

**Comment by heshamMassoud** [comment]
@butenkor The thing is the user of the library would have these values unset for a category and expect them to be unset after the sync. But actually they don't get unset and he would also not get information that it was skipped.

**Comment by butenkor** [comment]
Then it should be log level debug or info.
