### ISSUE TITLE
Bump minor versions from SDK 1.* 

### ISSUE THREAD

**Issue by pintomau** [commercetools/commercetools-sync-java#802]
Hello!

Context being https://github.com/commercetools/commercetools-sdk-java-v2/issues/227 .

Wondering if it's possible that, instead of overriding the bundled versions, to simply bump the Sync library dependency versions to 1.64.3.

Thanks.

**Comment by ahmetoz** [comment]
Hey @pintomau I was preparing a release today and upgraded sdk to v2 (before your request), would [v2.5.0](https://github.com/commercetools/commercetools-sync-java/blob/master/build.gradle#L13) be useful for you ? but having some issues on release process related to sonatype: https://github.com/commercetools/commercetools-sync-java/releases/tag/8.1.0

Could you please share your use case regarding to CompatSphereClient and sdk2 usage, as I have not tried using them together with this project yet ?

**Comment by ahmetoz** [comment]
Update: The issue on releasing 8.1.0 is resolved. I guess the oss sonatype is working slower than before.

**Comment by pintomau** [comment]
> Could you please share your use case regarding to CompatSphereClient and sdk2 usage, as I have not tried using them together with this project yet ?
We want to start migrating to SDK2 by slowly strangling out SDK1, we also want to take advantage of the lazy auth token initialization SDK2 already provides, which for our use case of a platform containing dozens of Commercetools projects, has an impact. The new builders are also useful for test cases.

>  would v2.5.0 be useful for you ?
I'm not sure since I can't find change logs or docs for the SDK1 v2.*, and I'm afraid to try it since majors usually mean breaking changes. I'd prefer to concentrate on migrating to SDK2.

Thanks.

**Comment by ahmetoz** [comment]
@pintomau  Thanks, we will try to check the use case!
I guess you could compare the change log here: https://github.com/commercetools/commercetools-jvm-sdk/compare/v1.64.0...v2.5.0

@jenschude do you have any plan to add release notes for the v2 release, I could not see much on release notes in this page after v1.64.0: http://commercetools.github.io/commercetools-jvm-sdk/apidocs/io/sphere/sdk/meta/ReleaseNotes.html#v1_64_0

**Comment by jenschude** [comment]
There are newer release notes. Seems the patch fixes overwrote them: https://github.com/commercetools/commercetools-jvm-sdk/blob/9c77fadd97e9b2c266fb933896d227cc2f1eec8e/commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java

main difference for 2.x was the dropped osgi support and the move to apache asynchttp client 5.1

**Comment by ahmetoz** [comment]
@jenschude thanks for the quick update!

@pintomau please check if the osgi support is important for you, the latest release does not effect any features related to sync-java so we migrated it to the latest already.

**Comment by pintomau** [comment]
I think our main issue would be the new asynchttp version. I'd have to invest more time to see what all the impact is.

So a new 8.0.* minor with the bumped versions is not possible at the moment?

I think for now, until we make sure we support the new asynchttp version, we'd simply try to override the referenced versions from Sync.

**Comment by jenschude** [comment]
We had to update as there the commons.io lib was outdated and could not be updated without an update of the async http client. Btw it could be that you still can use a pre 2.x version of the HTTP client even on a newer SDK version as the interfaces didn't changed

**Comment by pintomau** [comment]
We're in the testing phase of migration to SDK1 V2 with the SDK2 compat wrapper.

I think we're done here for now.

Thanks!
