### ISSUE TITLE
Product sync always produces AddToCategory and RemoveFromCategory actions, which lead to errors

### ISSUE THREAD

**Issue by se1by** [commercetools/commercetools-sync-java#816]
**Describe the bug**
Product sync always produces AddToCategory and RemoveFromCategory actions. This causes errors, as the AddToCategory action tries to add the product to a category that it is already in.

This is caused by the following code:

https://github.com/commercetools/commercetools-sync-java/blob/1625e2a5d94bb3865234fd9ae1d5ffabf204b18e/src/main/java/com/commercetools/sync/products/utils/ProductUpdateActionUtils.java#L179-L188

Calling `toResourceIdentifier` is not enough, as it returns a self reference. The following `equals` call will therefore call `Reference.equals`, which is not compatible to a `ResourceIdentifer`. 

**To Reproduce**
Just try to sync a product (which has a category).

**Expected behavior**
No UpdateActions regarding categories unless any changed.

**Comment by ahmetoz** [comment]
Hey @se1by I fixed the issue on the latest version, and it's released, could you check it please: https://github.com/commercetools/commercetools-sync-java/releases/tag/8.1.1, for now I'm closing the issue.
