### ISSUE TITLE
sync attribute prices

### ISSUE THREAD

**Issue by heshamMassoud** [commercetools/commercetools-sync-java#99]
For now only:

- [ ] setPrices  (always)
- [ ] price reference resolution.

-----
A custom comparator to compare the list of prices could be implemented. Only when they are not equal, then issue `setPrices` update action.

**Comment by butenkor** [comment]
For initial version we need only: value, channel and country.

**Comment by heshamMassoud** [comment]
currently this [bug](https://github.com/commercetools/commercetools-jvm-sdk/issues/1543) is affecting testing this implementation.

**Comment by heshamMassoud** [comment]
Duplicate of #101
